# Generated by Django 3.1.7 on 2021-03-07 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=40)),
                ('apellido', models.CharField(blank=True, max_length=40)),
                ('nit', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFactura', models.CharField(blank=True, max_length=60)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.cliente')),
            ],
        ),
    ]
